---
- name: Create images, vms, volumes and backups pool
  shell: ceph osd pool create {{ item.name }} {{ item.num }}
  with_items:
    - { name: "images", num: "{{ images_pool_pg }}" }
    - { name: "vms", num: "{{ vms_pool_pg }}" }
    - { name: "volumes", num: "{{ volumes_pool_pg }}" }
    - { name: "backups", num: "{{ backups_pool_pg }}" }

- name: Create glance, cinder and cinder-backup ceph-auth
  shell: ceph auth get-or-create {{ item.keyring }} mon 'allow r' osd {{ item.osd }}
  with_items:
    - { keyring: "client.glance", osd: "'allow class-read object_prefix rbd_children, allow rwx pool=images'" }
    - { keyring: "client.cinder", osd: "'allow class-read object_prefix rbd_children, allow rwx pool=volumes, allow rwx pool=vms, allow rx pool=images'" }
    - { keyring: "client.cinder-backup", osd: "'allow class-read object_prefix rbd_children, allow rwx pool=backups'" }
