---
- include_vars: "{{ nodesfile }}"

- name: Add ceph cluster to hosts file
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.ip }}"
    line: "{{ item.ip }} {{ item.hostname }}"
    state: present
  with_items: "{{ nodes }}"

- name: Remove 127.0.1.1
  lineinfile: dest=/etc/hosts regexp="127.0.1.1" state=absent

